env:
  es2021: true
  node: true
  browser: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 2020
rules:
  no-console: 0
  import/extensions: 0
  no-param-reassign: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
ignorePatterns: ['dist', 'webpack.config.cjs']